"""Field contract for centralized_v1 Stage2-Stage5 outputs."""

from __future__ import annotations

# Stage2 multimodal npz keys
C2_FILENAME = "filename"
C2_TIME_STR = "time_str"
C2_TIMESTAMP_UTC = "timestamp_utc"
C2_GRID_SHAPE = "grid_shape"
C2_RADAR_SHAPE = "radar_shape"
C2_RADAR_IMG = "radar_img"
C2_CLOUD_2D = "cloud_2d"
C2_MULTIMODAL_META_JSON = "multimodal_meta_json"
C2_WIND_RECORDS = "wind_records"
C2_CONTEXT_WIND_RECORDS = "context_wind_records"
C2_LOC_RECORDS = "loc_records"
C2_MOTION_RECORDS = "motion_records"
C2_CONTEXT_MOTION_RECORDS = "context_motion_records"
C2_FLIGHT_RAW_RECORDS = "flight_raw_records"
C2_CLOUD_FEATURE_RECORDS = "cloud_feature_records"

# Stage3 center json keys
C3_TIME_STR = "time_str"
C3_TIMESTAMP_UTC = "timestamp_utc"
C3_VOX_PATH = "vox_path"
C3_CENTER_ACTIVE = "ground_center_active"
C3_AGENT_IDS = "agent_ids"
C3_AGENT_TO_CENTER_ALLOWED = "agent_to_center_allowed"
C3_AGENT_LAT = "agent_lat"
C3_AGENT_LON = "agent_lon"
C3_AGENT_ALT = "agent_alt"
C3_AGENT_DELTA_TIME_MIN = "agent_delta_time_minutes"
C3_AGENT_DISTANCE_KM = "agent_distance_to_roi_km"
C3_AGENT_TIME_CONF = "agent_time_conf"
C3_AGENT_SPACE_CONF = "agent_space_conf"
C3_AGENT_JOINT_CONF = "agent_joint_conf"
C3_ALPHA = "time_conf_alpha"
C3_BETA = "space_conf_beta"

# Stage4 center npz keys
C4_RECON_U = "recon_u_3d"
C4_RECON_V = "recon_v_3d"
C4_RECON_CONF = "recon_confidence_3d"
C4_RECON_MASK = "recon_mask_3d"
C4_C_TIME_3D = "c_time_3d"
C4_C_SPACE_3D = "c_space_3d"
C4_C_JOINT_3D = "c_joint_3d"
C4_BLINDZONE_MASK = "blindzone_initialized_mask_3d"
C4_CLOUD_2D = "cloud_2d"
C4_POINT_EVAL_JSON = "point_eval_json"

# Stage5 center outputs
C5_REFINED_U = "refined_u_3d"
C5_REFINED_V = "refined_v_3d"
C5_REFINED_CONF = "refined_confidence_3d"
C5_FUTURE_WIND_U = "future_wind_u_3d"
C5_FUTURE_WIND_V = "future_wind_v_3d"
C5_FUTURE_WIND_CONF = "future_wind_confidence_3d"
C5_FUTURE_CLOUD_2D = "future_cloud_2d"
C5_FUTURE_CLOUD_METRICS_JSON = "future_cloud_metrics_json"
C5_DOWNLINK_ROI_JSON = "downlink_roi_by_flight_json"
